import { Inter } from "next/font/google";
import "./globals.css";
import { FaArrowUp } from "react-icons/fa";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen bg-gradient-to-b from-blue-50 to-red-100 z">
          <section className="h-24 z-50 fixed w-screen">
            <Navbar />
          </section>
    
          <div className="h-[calc(100vh-6rem)]">{children}</div>
        </div>
      </body>
    </html>
  );
}
