import { Inter } from "next/font/google";
import "./globals.css";
import { FaArrowUp } from "react-icons/fa";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen bg-gradient-to-b from-blue-50 to-green-100 z">
          <section className="md:fixed top-0 h-24 z-50 w-screen bg-gradient-to-b from-white to-transparent">
            <Navbar />
          </section>

          <div className="h-[calc(100vh-6rem)]">{children}</div>
        </div>
      </body>
    </html>
  );
}
